# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Carrera.create(nombre:'Ingenieria Agricola',creditos:180)
Carrera.create(nombre:'Ingenieria Civil',creditos:180)
Carrera.create(nombre:'Ingenieria de Sistema y Computacion',creditos:165)
Carrera.create(nombre:'Ingenieria Electrica',creditos:167)
Carrera.create(nombre:'Ingenieria Electronica',creditos:172)
Carrera.create(nombre:'Ingenieria Indusctrial',creditos:168)
Carrera.create(nombre:'Ingenieria Mecanica',creditos:180)
Carrera.create(nombre:'Ingenieria Mecatronica',creditos:179)
Carrera.create(nombre:'Ingenieria Quimica',creditos:180)

Materium.create(nombre:'Calculo Diferencial',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Calculo Diferencial en una Variable',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Algebra Lineal',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Algebra Lineal Basica',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Calculo Integral',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Calculo Integral en una Variable',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Calculo en Varias Variables',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Calculo Vectorial',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Ecuaciones Diferenciales',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Calculo de Ecuaciones Diferenciales',4,tipo:'Fundamentacion')
Materium.create(nombre:'Probabilidad',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Inferencia Estadistica',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Fundamentos de Mecanica',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Fundamentos de Electricidad y Magnetismo',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Programacion de Computadores',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Programacion Orientada a Objetos',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Fundamentos de Oscilaciones, Ondas y Optica',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Bilogia General',creditos: 3,tipo:'Fundamentacion')
Materium.create(nombre:'Principio de Quimica',creditos: 3,tipo:'Fundamentacion')
Materium.create(nombre:'Fisiologia Vegetal',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Dibujo Basico',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Metodos Numericos',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Modelacion Matematica',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Aplicacion de Elementos Finitos',creditos: 4,tipo:'Fundamentacion')
Materium.create(nombre:'Modelos y Simulacion',creditos: 4,tipo:'Fundamentacion')